package org.group16.Model.Buildings;

public enum BuildingType {
    //economy
    SMALL_STONE_GATEHOUSE,
    //economy
    LARGE_STONE_GATEHOUSE,
    //war
    DRAWBRIDGE,
    //war
    LOOKOUT_TOWER,
    //war
    PERIMETER_TOWER,
    //war
    DEFENCE_TURRET,
    //war
    SQUARE_TOWER,
    //war
    ROUND_TOWER,
    //economy
    ARMOURY,
    //economy
    BARRACKS,
    //economy
    MERCENARY_POST,
    //economy
    ENGINEER_GUILD,
    //war
    KILLING_PIT,
    //economy
    INN,
    //economy
    MILL,
    //economy
    IRON_MINE,
    //economy
    MARKET,
    //economy
    OX_TETHER,
    //economy
    PITCH_RIG,
    //economy
    QUARRY,
    //economy
    STOCKPILE,
    //economy
    WOOD_CUTTER,
    //economy
    HOVEL,
    //economy
    CHURCH,
    //economy
    CATHEDRAL,
    //economy
    ARMOURER,
    //economy
    BLACKSMITH,
    //economy
    FLETCHER,
    //economy
    POLE_TURNER,
    //economy
    OIL_SMELTER,
    //war?
    PITCH_DITCH,
    //TODO : ????
    //war?
    CAGED_WAR_DOGS,
    //TODO : ????
    //war?
    SIEGE_TENT,
    //economy
    STABLE,
    //economy
    APPLE_ORCHARD,
    //economy
    DIARY_FARMER,
    //economy
    HOPS_FARMER,
    //economy
    HUNTER_POST,
    //economy
    WHEAT_FARMER,
    //economy
    BAKERY,
    //economy
    BREWER,
    //economy
    GRANARY,
    ;
}
